server:
  http:
    addr: 0.0.0.0:8000
    timeout: 2s
  grpc:
    addr: 0.0.0.0:19087
    timeout: 2s
data:
  database:
    source: "root:@tcp(localhost:13306)/ccnubox?charset=utf8mb4&parseTime=True&loc=Local"
    #    source: "root:12345678@tcp(127.0.0.1:13306)/MuxiClass?charset=utf8mb4&parseTime=True&loc=Local"
    logPath: "/var/log/sql_log"
    logFileName: "sql.log"
  redis:
    addr: "localhost:6379"
    password: ""
    #    addr: "127.0.0.1:16379"
    read_timeout: 0.2s
    write_timeout: 0.2s
registry:
  etcd:
#    addr: "Etcd:2379"
    addr: "127.0.0.1:2379"
    username: root
    password: ""
zaplog:
  # 日志等级
  log_level: "info"
  # 日志的格式
  log_format: "json"
  # 日志文件的路径
  log_path: "/var/log/app_log"
  # 日志文件的名字
  log_file_name: "app.log"
  # 日志文件的最大大小MB
  log_file_max_size: 100
  # 【日志分割】日志备份文件最多数量
  log_file_max_backups: 5
  # 日志保留时间，单位: 天 (day)
  log_max_age: 30
  # 日志是否压缩
  log_compress: false
  # 日志是否输出到控制台
  log_stdout: false
schoolday:  # 相关时间,格式"2025-07-05"
  # 这个可以热更新，修改后保存即可
  holidayTime: "2025-07-05" #放假第一天
  schoolTime: "2025-02-17" #上学第一天
