apiVersion: v1
kind: ConfigMap
metadata:
  name: ccnube-config
  namespace: ccnube
data:
  be-banner.yaml: |
    grpc:
      server:
        name: "banner"
        weight: 100
        addr: ":19080"
        etcdTTL: 60

    etcd:
      endpoints:
        - "etcd-0.etcd:2379"
      username: root
      password: ""

    redis:
      addr: "redis-0.redis:6379"
      password: ""

    mysql:
      dsn: "root:@tcp(mysql-0.mysql:3306)/ccnubox?charset=utf8mb4&parseTime=True&loc=Local"
    
    log:
      path: "./logs/app.log"  # æ—¥å¿—æ–‡ä»¶è·¯å¾„
      maxSize: 100           # å•ä¸ªæ—¥å¿—æ–‡ä»¶çš„æœ€å¤§å¤§å°ï¼ˆMBï¼‰
      maxBackups: 7          # ä¿ç•™æ—§æ—¥å¿—æ–‡ä»¶çš„æœ€å¤§æ•°é‡
      maxAge: 30             # æ—¥å¿—æ–‡ä»¶ä¿ç•™å¤©æ•°
      compress: 1             # æ˜¯å¦å‹ç¼©æ—§æ—¥å¿—æ–‡ä»¶ï¼ˆ1 è¡¨ç¤ºå‹ç¼©ï¼Œ0 è¡¨ç¤ºä¸å‹ç¼©ï¼‰

  be-calendar.yaml: |
    grpc:
      server:
        name: "calendar"
        weight: 100
        addr: ":19081"
        etcdTTL: 60
      client:
        feed:
          endpoint: "discovery:///feed"

    etcd:
      endpoints:
        - "etcd-0.etcd:2379"
      username: root
      password: ""

    redis:
      addr: "redis-0.redis:6379"
      password: ""

    mysql:
      dsn: "root:@tcp(mysql-0.mysql:3306)/ccnubox?charset=utf8mb4&parseTime=True&loc=Local"

    qiniu:
      accessKey : "xxxxxxxxxxx"#ç§˜é’¥
      secretKey : "xxxxxxxxxxx"#ç§˜é’¥x2
      bucket: "xxxxxxxxxxx"#ä»“åº“å
      domain : "xxxxxxxxxxx"#é»˜è®¤åŸŸå
      baseName : "ccnuCalendar"

    calendarController:
      durationTime: 24 #çˆ¬å–é¢‘ç‡,å•ä½æ˜¯å°æ—¶

    #å‡æœŸè‡ªåŠ¨æé†’
    holidayController:
      durationTime: 1 #å•ä½æ˜¯å°æ—¶,æ¯å¤šå°‘å°æ—¶å°è¯•å»è·å–ä¸€æ¬¡,è¿™ä¸ªåº”è¯¥æ˜¯å†™æ­»çš„,ä¸è¦æ›´æ”¹,ä¸€å¤©ä¸€æ¬¡å¾ˆåˆç†
      advanceDay: 4 #æå‰å››å¤©è¿›è¡Œæé†’
    
    log:
      path: "./logs/app.log"  # æ—¥å¿—æ–‡ä»¶è·¯å¾„
      maxSize: 100           # å•ä¸ªæ—¥å¿—æ–‡ä»¶çš„æœ€å¤§å¤§å°ï¼ˆMBï¼‰
      maxBackups: 7          # ä¿ç•™æ—§æ—¥å¿—æ–‡ä»¶çš„æœ€å¤§æ•°é‡
      maxAge: 30             # æ—¥å¿—æ–‡ä»¶ä¿ç•™å¤©æ•°
      compress: 1             # æ˜¯å¦å‹ç¼©æ—§æ—¥å¿—æ–‡ä»¶ï¼ˆ1 è¡¨ç¤ºå‹ç¼©ï¼Œ0 è¡¨ç¤ºä¸å‹ç¼©ï¼‰
  be-ccnu.yaml: |
    etcd:
      endpoints:
        - "etcd-0.etcd:2379"
      username: root
      password: ""

    grpc:
      server:
        name: "ccnu"
        weight: 100
        addr: ":19082"
        etcdTTL: 60


    log:
      path: "./logs/app.log"  # æ—¥å¿—æ–‡ä»¶è·¯å¾„
      maxSize: 100           # å•ä¸ªæ—¥å¿—æ–‡ä»¶çš„æœ€å¤§å¤§å°ï¼ˆMBï¼‰
      maxBackups: 7          # ä¿ç•™æ—§æ—¥å¿—æ–‡ä»¶çš„æœ€å¤§æ•°é‡
      maxAge: 30             # æ—¥å¿—æ–‡ä»¶ä¿ç•™å¤©æ•°
      compress: 1             # æ˜¯å¦å‹ç¼©æ—§æ—¥å¿—æ–‡ä»¶ï¼ˆ1 è¡¨ç¤ºå‹ç¼©ï¼Œ0 è¡¨ç¤ºä¸å‹ç¼©ï¼‰
  be-class.yaml: |
    server:
      http:
        addr: 0.0.0.0:18000
        timeout: 10s
      grpc:
        addr: 0.0.0.0:19083
        timeout: 10s
    data:
      es:
        url: "http://elasticsearch-0.elasticsearch:9200"
        setsniff: false
        username: "elastic"
        password: ""
        #é‡å¯åæ˜¯å¦ä¿ç•™æ•°æ®
        keepDataAfterRestart: true
        classroom: "/data/conf/classrooms.json"
    registry:
      etcd:
        addr: "etcd-0.etcd:2379"
        username: root
        password: ""

  be-classlist.yaml: |
    server:
      name: "be-classlist"  # æ–°å¢å­—æ®µï¼šæœåŠ¡åç§°
      grpc:
        network: "tcp"          #ç½‘ç»œç±»å‹ï¼Œé€šå¸¸ä¸º tcp
        addr: "0.0.0.0:19084"
        timeout: 2              # æ³¨æ„ï¼šè¿™é‡Œå•ä½æ˜¯ç§’
      waitCrawTime: 5000        # ç­‰å¾…çˆ¬è™«æŠ“å–æ•°æ®çš„æ—¶é—´ï¼Œå•ä½ms
      classExpiration: 604800    # è¯¾ç¨‹è¿‡æœŸæ—¶é—´ï¼Œå•ä½sï¼Œä¾‹å¦‚ 1 å¤©
      recycleExpiration: 2592000 # å›æ”¶ç«™è¯¾ç¨‹è¿‡æœŸæ—¶é—´ï¼Œå•ä½s
      blackListExpiration: 60 # é»‘åå•è¿‡æœŸæ—¶é—´ï¼Œå•ä½s

    data:
      database:
        source: "root:@tcp(localhost:13306)/ccnubox?charset=utf8mb4&parseTime=True&loc=Local"
        logPath: "/var/log/sql_log"
        logFileName: "sql.log"
      redis:
        addr: "localhost:6379"
        password: ""
        read_timeout: 200       # æ³¨æ„ï¼šå•ä½ä¸ºæ¯«ç§’
        write_timeout: 200      # æ³¨æ„ï¼šå•ä½ä¸ºæ¯«ç§’

    registry:
      etcd:
        addr: "127.0.0.1:2379"
        username: "root"
        password: ""
      usersvc: "discovery:///user"               # ç”¨æˆ·æœåŠ¡åœ°å€

    zaplog:
      ##æ—¥å¿—çº§åˆ«
      log_level: "info"
      ##æ—¥å¿—æ ¼å¼
      log_format: "json"
      ##æ—¥å¿—è·¯å¾„
      log_path: "/var/log/app_log"
      ##æ—¥å¿—æ–‡ä»¶å
      log_file_name: "app.log"
      ##æ—¥å¿—æ–‡ä»¶æœ€å¤§å¤§å°
      log_file_max_size: 100
      ##æ—¥å¿—æ–‡ä»¶æœ€å¤§å¤‡ä»½æ•°
      log_file_max_backups: 5
      ##æ—¥å¿—æ–‡ä»¶æœ€å¤§ä¿ç•™å¤©æ•°
      log_max_age: 30
      ##æ˜¯å¦å‹ç¼©
      log_compress: false
      ##æ˜¯å¦è¾“å‡ºåˆ°æ§åˆ¶å°
      log_stdout: false

    schoolday:
      holidayTime: "2025-07-05"
      schoolTime: "2025-02-17"

  be-counter.yaml: |
    grpc:
      server:
        name: "Counter"
        weight: 100
        addr: ":19085"
        etcdTTL: 60

    etcd:
      endpoints:
        - "etcd-0.etcd:2379"
      username: root
      password: ""

    redis:
      addr: "redis-0.redis:6379"
      password: ""

    countLevel:
      low: 0 #è½®è¯¢ä½ä½èµ·å§‹ç‚¹
      middle: 3 #è½®è¯¢ä¸­ä½èµ·å§‹ç‚¹
      high: 6 #è½®è¯¢é«˜ä½èµ·å§‹ç‚¹
      step: 3 #è½®è¯¢é™çº§ä¸å‡çº§æ­¥æ•°,å³ä¸€æ¬¡æ›´æ”¹ä¸€çº§

    log:
      path: "./logs/app.log"  # æ—¥å¿—æ–‡ä»¶è·¯å¾„
      maxSize: 100           # å•ä¸ªæ—¥å¿—æ–‡ä»¶çš„æœ€å¤§å¤§å°ï¼ˆMBï¼‰
      maxBackups: 7          # ä¿ç•™æ—§æ—¥å¿—æ–‡ä»¶çš„æœ€å¤§æ•°é‡
      maxAge: 30             # æ—¥å¿—æ–‡ä»¶ä¿ç•™å¤©æ•°
      compress: 1             # æ˜¯å¦å‹ç¼©æ—§æ—¥å¿—æ–‡ä»¶ï¼ˆ1 è¡¨ç¤ºå‹ç¼©ï¼Œ0 è¡¨ç¤ºä¸å‹ç¼©ï¼‰
  be-department.yaml: |
    grpc:
      server:
        name: "department"
        weight: 100
        addr: ":19086"
        etcdTTL: 60

    redis:
      addr: "redis-0.redis:6379"
      password: ""

    etcd:
      endpoints:
        - "etcd-0.etcd:12379"
      username: root
      password: ""

    mysql:
      dsn: "root:@tcp(mysql-0.mysql:3306)/ccnubox?charset=utf8mb4&parseTime=True&loc=Local"

    log:
      path: "./logs/app.log"  # æ—¥å¿—æ–‡ä»¶è·¯å¾„
      maxSize: 100           # å•ä¸ªæ—¥å¿—æ–‡ä»¶çš„æœ€å¤§å¤§å°ï¼ˆMBï¼‰
      maxBackups: 7          # ä¿ç•™æ—§æ—¥å¿—æ–‡ä»¶çš„æœ€å¤§æ•°é‡
      maxAge: 30             # æ—¥å¿—æ–‡ä»¶ä¿ç•™å¤©æ•°
      compress: 1             # æ˜¯å¦å‹ç¼©æ—§æ—¥å¿—æ–‡ä»¶ï¼ˆ1 è¡¨ç¤ºå‹ç¼©ï¼Œ0 è¡¨ç¤ºä¸å‹ç¼©ï¼‰
  be-elecprice.yaml: |
    mysql:
      dsn: "root:@tcp(mysql-0.mysql:3306)/ccnubox?charset=utf8mb4&parseTime=True&loc=Local"

    etcd:
      endpoints:
        - "etcd-0.etcd:2379"
      username: root
      password: ""

    grpc:
      server:
        name: "elecprice"
        weight: 100
        addr: ":19087"
        etcdTTL: 60
      client:
        feed:
          endpoint: "discovery:///feed"

    #ç”µè´¹æˆç»©
    elecpriceController:
      durationTime: 24 # æ£€æŸ¥å‘¨æœŸ,æ¯24å°æ—¶æ£€æŸ¥ä¸€æ¬¡

    log:
      path: "./logs/app.log"  # æ—¥å¿—æ–‡ä»¶è·¯å¾„
      maxSize: 100           # å•ä¸ªæ—¥å¿—æ–‡ä»¶çš„æœ€å¤§å¤§å°ï¼ˆMBï¼‰
      maxBackups: 7          # ä¿ç•™æ—§æ—¥å¿—æ–‡ä»¶çš„æœ€å¤§æ•°é‡
      maxAge: 30             # æ—¥å¿—æ–‡ä»¶ä¿ç•™å¤©æ•°
      compress: 1             # æ˜¯å¦å‹ç¼©æ—§æ—¥å¿—æ–‡ä»¶ï¼ˆ1 è¡¨ç¤ºå‹ç¼©ï¼Œ0 è¡¨ç¤ºä¸å‹ç¼©ï¼‰
  be-feed.yaml: |
    mysql:
      dsn: "root:@tcp(mysql-0.mysql:3306)/ccnubox?charset=utf8mb4&parseTime=True&loc=Local"
    etcd:
      endpoints:
        - "localhost:12379"
      username: root
      password: ""

    grpc:
      server:
        name: "feed"
        weight: 100
        addr: ":19088"
        etcdTTL: 60
      client:
        feedUserCount:
          endpoint: "discovery:///feedUserCount"
        classlist:
          endpoint: "discovery:///be-classlist"
        grade:
          endpoint: "discovery:///grade"
        user:
          endpoint: "discovery:///user"

    kafka:
      addrs:
        - "kafka-0.kafka:9092"

    redis:
      addr: "redis-0.redis:6379"
      password: ""

    muxiController:
      durationTime: 86400

    #æ¶ˆè´¹è€…çš„æ¶ˆè´¹é…ç½®
    consume:
      consumeTime: 1 #å¼ºåˆ¶æ’å…¥çš„æ—¶é—´(å¦‚æœé•¿æœŸæ²¡æœ‰æ¶ˆæ¯è¢«æ¶ˆè´¹çš„è¯),å•ä½æ˜¯åˆ†é’Ÿ
      consumeNum: 2 #æ‰¹é‡å­˜å…¥,æ¯æ¬¡æœ€å¤šä¸€æ¬¡å­˜å…¥500æ¡æ•°æ®(è®¾ç½®æœ€å¤§å€¼ä¸èƒ½è¶…è¿‡ä¸€åƒ,å¦åˆ™è¯·è‡ªè¡Œä¿®æ”¹daoå±‚çš„gormæ’å…¥feedEventçš„æœ€å¤§ä¸Šé™å€¼)

    #æå…‰æ¨é€é…ç½®
    jpushConfig:
      appKey: "xxx"
      masterSecret: "xxx"

    log:
      path: "./logs/app.log"  # æ—¥å¿—æ–‡ä»¶è·¯å¾„
      maxSize: 100           # å•ä¸ªæ—¥å¿—æ–‡ä»¶çš„æœ€å¤§å¤§å°ï¼ˆMBï¼‰
      maxBackups: 7          # ä¿ç•™æ—§æ—¥å¿—æ–‡ä»¶çš„æœ€å¤§æ•°é‡
      maxAge: 30             # æ—¥å¿—æ–‡ä»¶ä¿ç•™å¤©æ•°
      compress: 1             # æ˜¯å¦å‹ç¼©æ—§æ—¥å¿—æ–‡ä»¶ï¼ˆ1 è¡¨ç¤ºå‹ç¼©ï¼Œ0 è¡¨ç¤ºä¸å‹ç¼©ï¼‰
  be-grade.yaml: |
    mysql:
      dsn: "root:@tcp(mysql-0.mysql:3306)/ccnubox?charset=utf8mb4&parseTime=True&loc=Local"
    etcd:
      endpoints:
        - "etcd-0.etcd:2379"
      username: root
      password: ""

    grpc:
      server:
        name: "grade"
        weight: 100
        addr: ":19089"
        etcdTTL: 60
      client:
        classlist:
          endpoint: "discovery:///be-classlist"
        user:
          endpoint: "discovery:///user"
        counter:
          endpoint: "discovery:///counter"
        feed:
          endpoint: "discovery:///feed"
        ccnu:
          endpoint: "discovery:///ccnu"

    #æˆç»©è‡ªåŠ¨æé†’
    gradeController:
      high: 1  #å•ä½æ˜¯åˆ†é’Ÿ
      middle: 30 #å•ä½æ˜¯åˆ†é’Ÿ
      low: 60 #å•ä½æ˜¯åˆ†é’Ÿ

    log:
      path: "./logs/app.log"  # æ—¥å¿—æ–‡ä»¶è·¯å¾„
      maxSize: 100           # å•ä¸ªæ—¥å¿—æ–‡ä»¶çš„æœ€å¤§å¤§å°ï¼ˆMBï¼‰
      maxBackups: 7          # ä¿ç•™æ—§æ—¥å¿—æ–‡ä»¶çš„æœ€å¤§æ•°é‡
      maxAge: 30             # æ—¥å¿—æ–‡ä»¶ä¿ç•™å¤©æ•°
      compress: 1             # æ˜¯å¦å‹ç¼©æ—§æ—¥å¿—æ–‡ä»¶ï¼ˆ1 è¡¨ç¤ºå‹ç¼©ï¼Œ0 è¡¨ç¤ºä¸å‹ç¼©ï¼‰
  be-infosum.yaml: |
    grpc:
      server:
        name: "info_sum"
        weight: 100
        addr: ":19090"
        etcdTTL: 60

    etcd:
      endpoints:
        - "etcd-0.etcd:2379"
      username: root
      password: ""

    redis:
      addr: "redis-0.redis:6379"
      password: ""

    mysql:
      dsn: "root:@tcp(mysql-0.mysql:3306)/ccnubox?charset=utf8mb4&parseTime=True&loc=Local"
    log:
      path: "./logs/app.log"  # æ—¥å¿—æ–‡ä»¶è·¯å¾„
      maxSize: 100           # å•ä¸ªæ—¥å¿—æ–‡ä»¶çš„æœ€å¤§å¤§å°ï¼ˆMBï¼‰
      maxBackups: 7          # ä¿ç•™æ—§æ—¥å¿—æ–‡ä»¶çš„æœ€å¤§æ•°é‡
      maxAge: 30             # æ—¥å¿—æ–‡ä»¶ä¿ç•™å¤©æ•°
      compress: 1             # æ˜¯å¦å‹ç¼©æ—§æ—¥å¿—æ–‡ä»¶ï¼ˆ1 è¡¨ç¤ºå‹ç¼©ï¼Œ0 è¡¨ç¤ºä¸å‹ç¼©ï¼‰

  be-user.yaml: |
    mysql:
      dsn: "root:@tcp(mysql-0.mysql:3306)/ccnubox?charset=utf8mb4&parseTime=True&loc=Local"

    redis:
      addr: "redis-0.redis:6379"
      password: ""

    etcd:
      endpoints:
        - "etcd-0.etcd:12379"
      username: root
      password: ""
    log:
      path: "./logs/user.log"  # æ—¥å¿—æ–‡ä»¶è·¯å¾„
      maxSize: 100           # å•ä¸ªæ—¥å¿—æ–‡ä»¶çš„æœ€å¤§å¤§å°ï¼ˆMBï¼‰
      maxBackups: 7          # ä¿ç•™æ—§æ—¥å¿—æ–‡ä»¶çš„æœ€å¤§æ•°é‡
      maxAge: 30             # æ—¥å¿—æ–‡ä»¶ä¿ç•™å¤©æ•°
      compress: 1             # æ˜¯å¦å‹ç¼©æ—§æ—¥å¿—æ–‡ä»¶ï¼ˆ1 è¡¨ç¤ºå‹ç¼©ï¼Œ0 è¡¨ç¤ºä¸å‹ç¼©ï¼‰

    grpc:
      server:
        name: "user"
        weight: 100
        addr: ":19091"
        etcdTTL: 60
      client:
        ccnu:
          endpoint: "discovery:///ccnu"

  be-website.yaml: |
    grpc:
      server:
        name: "website"
        weight: 100
        addr: ":19092"
        etcdTTL: 60

    etcd:
      endpoints:
        - "etcd-0.etcd:12379"
      username: root
      password: ""

    redis:
      addr: "redis-0.redis:6379"
      password: ""

    mysql:
      dsn: "root:@tcp(mysql-0.mysql:3306)/ccnubox?charset=utf8mb4&parseTime=True&loc=Local"

    log:
      path: "./logs/app.log"  # æ—¥å¿—æ–‡ä»¶è·¯å¾„
      maxSize: 100           # å•ä¸ªæ—¥å¿—æ–‡ä»¶çš„æœ€å¤§å¤§å°ï¼ˆMBï¼‰
      maxBackups: 7          # ä¿ç•™æ—§æ—¥å¿—æ–‡ä»¶çš„æœ€å¤§æ•°é‡
      maxAge: 30             # æ—¥å¿—æ–‡ä»¶ä¿ç•™å¤©æ•°
      compress: 1             # æ˜¯å¦å‹ç¼©æ—§æ—¥å¿—æ–‡ä»¶ï¼ˆ1 è¡¨ç¤ºå‹ç¼©ï¼Œ0 è¡¨ç¤ºä¸å‹ç¼©ï¼‰

  bff.yaml: |
    http:
      addr: ":8080"

    redis:
      addr: "redis-0.redis:6379"
      password: ""


    etcd:
      endpoints:
        - "etcd-0.etcd:2379"
      username: root
      password: ""

    rootistrators:
      - "1234123456"

    grpc:
      client:
        ccnu:
          endpoint: "discovery:///ccnu"
          retryCnt: 3    # å…·å¤‡é‡è¯•è£…é¥°æ—¶çš„é‡è¯•æ¬¡æ•°
        user:
          endpoint: "discovery:///user"
        static:
          endpoint: "discovery:///static"
        feed:
          endpoint: "discovery:///feed"
        banner:
          endpoint: "discovery:///banner"
        calendar:
          endpoint: "discovery:///calendar"
        department:
          endpoint: "discovery:///department"
        website:
          endpoint: "discovery:///website"
        elecprice:
          endpoint: "discovery:///elecprice"
        classlist:
          endpoint: "discovery:///be-classlist"
        classService:
          endpoint: "discovery:///be-class"
        feedbackHelp:
          endpoint: "discovery:///feedback_help"
        grade:
          endpoint: "discovery:///grade"
        infoSum:
          endpoint: "discovery:///info_sum"
        counter:
          endpoint: "discovery:///counter"
        card:
          endpoint: "discovery:///card"

    jwt:
      jwtKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      refreshKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

    oss:
      accessKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      secretKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      bucketName: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      domainName: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx # CDN åŸŸå

    # æ—¥å¿—é…ç½®
    log:
      path: "./logs/app.log"  # æ—¥å¿—æ–‡ä»¶è·¯å¾„
      maxSize: 100           # å•ä¸ªæ—¥å¿—æ–‡ä»¶çš„æœ€å¤§å¤§å°ï¼ˆMBï¼‰
      maxBackups: 7          # ä¿ç•™æ—§æ—¥å¿—æ–‡ä»¶çš„æœ€å¤§æ•°é‡
      maxAge: 30             # æ—¥å¿—æ–‡ä»¶ä¿ç•™å¤©æ•°
      compress: 1             # æ˜¯å¦å‹ç¼©æ—§æ—¥å¿—æ–‡ä»¶ï¼ˆ1 è¡¨ç¤ºå‹ç¼©ï¼Œ0 è¡¨ç¤ºä¸å‹ç¼©ï¼‰

    # Prometheus é…ç½®
    prometheus:
      namespace: "ccnubox" # Prometheus å‘½åç©ºé—´ï¼Œé€šå¸¸ä¸ºé¡¹ç›®åç§°

      routerCounter:
        name: "http_requests_total"  # è·¯ç”±è¯·æ±‚æ€»æ•°æŒ‡æ ‡åç§°
        help: "Total number of HTTP requests" # æŒ‡æ ‡è¯´æ˜

      activeConnections:
        name: "active_connections"  # æ´»è·ƒè¿æ¥æŒ‡æ ‡åç§°
        help: "Number of active connections per route" # æŒ‡æ ‡è¯´æ˜

      durationTime:
        name: "http_request_duration_seconds"  # è¯·æ±‚æ—¶é•¿ç›´æ–¹å›¾åç§°
        help: "Histogram of response times for HTTP requests" # æŒ‡æ ‡è¯´æ˜
  init.sql: |  # ğŸ‘ˆ å…³é”®ç‚¹ï¼šæ–‡ä»¶åå¿…é¡»æ˜¯ .sql æˆ– .sh
    CREATE DATABASE IF NOT EXISTS ccnubox;
  be-class-classrooms.json: |
    {
      "class_rooms": [
        "3101",
        "3102",
        "3103",
        "3104",
        "3106",
        "3108",
        "3110",
        "3111",
        "3112",
        "3113",
        "3114",
        "3115",
        "3116",
        "3117",
        "3118",
        "3201",
        "3202",
        "3203",
        "3204",
        "3205",
        "3206",
        "3207",
        "3208",
        "3209",
        "3210",
        "3211",
        "3212",
        "3213",
        "3214",
        "3215",
        "3216",
        "3217",
        "3218",
        "3300",
        "3301",
        "3302",
        "3303",
        "3304",
        "3305",
        "3306",
        "3307",
        "3308",
        "3309",
        "3310",
        "3318",
        "3319",
        "3401",
        "3501",
        "3502",
        "3505",
        "7101",
        "7103",
        "7104",
        "7105",
        "7106",
        "7107",
        "7108",
        "7109",
        "7110",
        "7201",
        "7203",
        "7204",
        "7205",
        "7206",
        "7207",
        "7208",
        "7209",
        "7211",
        "7301",
        "7303",
        "7304",
        "7305",
        "7306",
        "7307",
        "7308",
        "7309",
        "7310",
        "7311",
        "7505",
        "7506",
        "8102",
        "8103",
        "8104",
        "8105",
        "8106",
        "8107",
        "8108",
        "8109",
        "8110",
        "8111",
        "8112",
        "8201",
        "8202",
        "8203",
        "8204",
        "8205",
        "8207",
        "8208",
        "8209",
        "8210",
        "8211",
        "8212",
        "8213",
        "8214",
        "8215",
        "8216",
        "8301",
        "8302",
        "8303",
        "8304",
        "8305",
        "8307",
        "8308",
        "8309",
        "8310",
        "8311",
        "8312",
        "8313",
        "8314",
        "8315",
        "8316",
        "8401",
        "8402",
        "8403",
        "8404",
        "8405",
        "8406",
        "8407",
        "8408",
        "8409",
        "8410",
        "8411",
        "8412",
        "8413",
        "8414",
        "8416",
        "8501",
        "8502",
        "8503",
        "8504",
        "8505",
        "8506",
        "8507",
        "8508",
        "8509",
        "8510",
        "8511",
        "8512",
        "8513",
        "8514",
        "8515",
        "8516",
        "8616",
        "8617",
        "8618",
        "8701",
        "8702",
        "8703",
        "8704",
        "8705",
        "8706",
        "8707",
        "8709",
        "8716",
        "8717",
        "9101",
        "9102",
        "9201",
        "9202",
        "9203",
        "9301",
        "9302",
        "9303",
        "9401",
        "9402",
        "9403",
        "9501",
        "9523",
        "9532",
        "9538",
        "9726",
        "9728",
        "9730",
        "9732",
        "10103",
        "10104",
        "10105",
        "10106",
        "10201",
        "10202",
        "10203",
        "10204",
        "10205",
        "10207",
        "10209",
        "10301",
        "10302",
        "10303",
        "10304",
        "10305",
        "10306",
        "10307",
        "10308",
        "10313",
        "10401",
        "10402",
        "10403",
        "10404",
        "10405",
        "10406",
        "10407",
        "10408",
        "10502",
        "10503",
        "10504",
        "10505",
        "10506",
        "10507",
        "10508",
        "10601",
        "10602",
        "10603",
        "10604",
        "10605",
        "10606",
        "10607",
        "10609",
        "10613",
        "10701",
        "10702",
        "10703",
        "10704",
        "10705",
        "10706",
        "10708",
        "10709",
        "10801",
        "10803",
        "n104",
        "n107",
        "n109",
        "n111",
        "n112",
        "n113",
        "n115",
        "n117",
        "n119",
        "n201",
        "n202",
        "n204",
        "n205",
        "n206",
        "n207",
        "n208",
        "n209",
        "n210",
        "n211",
        "n212",
        "n213",
        "n214",
        "n215",
        "n216",
        "n217",
        "n219",
        "n221",
        "n223",
        "n301",
        "n302",
        "n303",
        "n304",
        "n306",
        "n307",
        "n308",
        "n310",
        "n311",
        "n312",
        "n313",
        "n314",
        "n315",
        "n316",
        "n317",
        "n318",
        "n319",
        "n320",
        "n321",
        "n323",
        "n325",
        "n327"
      ]
    }
