# yaml 配置
version: "3.7"
services:
  es:
    image: elasticsearch:7.17.23
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=12345678  # 设置 elastic 用户密码
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # 限制内存使用
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "./esdata:/usr/share/elasticsearch/data"
  classService:
    image: extra_class
    ports:
      - "18000:18000"
      - "19000:19000"
    volumes:
      - "../configs/config.yaml:/data/conf/config.yaml"