name: 部署各个服务到集群


on:
#  push:
#    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-be-banner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          # 设置 Docker Buildx（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
          # 登录阿里云 Docker Registry
      - name: Log in to Aliyun Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          registry: crpi-vgud82zncz8nwfuc.cn-hangzhou.personal.cr.aliyuncs.com
      - name: build and push image
        run: |
          chmod +x ./build-be-banner.sh
          ./build-be-banner.sh  ${{ secrets.IMAGE_REPO }}
  build-be-calendar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # 设置 Docker Buildx（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        # 登录阿里云 Docker Registry
      - name: Log in to Aliyun Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          registry: crpi-vgud82zncz8nwfuc.cn-hangzhou.personal.cr.aliyuncs.com
      - name: build and push image
        run: |
          chmod +x ./build-be-calendar.sh
          ./build-be-calendar.sh  ${{ secrets.IMAGE_REPO }}
  build-be-ccnu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # 设置 Docker Buildx（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        # 登录阿里云 Docker Registry
      - name: Log in to Aliyun Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          registry: crpi-vgud82zncz8nwfuc.cn-hangzhou.personal.cr.aliyuncs.com
      - name: build and push image
        run: |
          chmod +x ./build-be-ccnu.sh
          ./build-be-ccnu.sh  ${{ secrets.IMAGE_REPO }}
  build-be-class:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # 设置 Docker Buildx（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        # 登录阿里云 Docker Registry
      - name: Log in to Aliyun Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          registry: crpi-vgud82zncz8nwfuc.cn-hangzhou.personal.cr.aliyuncs.com
      - name: build and push image
        run: |
          chmod +x ./build-be-class.sh
          ./build-be-class.sh  ${{ secrets.IMAGE_REPO }}
  build-be-classlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # 设置 Docker Buildx（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        # 登录阿里云 Docker Registry
      - name: Log in to Aliyun Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          registry: crpi-vgud82zncz8nwfuc.cn-hangzhou.personal.cr.aliyuncs.com
      - name: build and push image
        run: |
          chmod +x ./build-be-classlist.sh
          ./build-be-classlist.sh  ${{ secrets.IMAGE_REPO }}
  build-be-counter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # 设置 Docker Buildx（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        # 登录阿里云 Docker Registry
      - name: Log in to Aliyun Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          registry: crpi-vgud82zncz8nwfuc.cn-hangzhou.personal.cr.aliyuncs.com
      - name: build and push image
        run: |
          chmod +x ./build-be-counter.sh
          ./build-be-counter.sh  ${{ secrets.IMAGE_REPO }}
  build-be-department:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # 设置 Docker Buildx（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        # 登录阿里云 Docker Registry
      - name: Log in to Aliyun Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          registry: crpi-vgud82zncz8nwfuc.cn-hangzhou.personal.cr.aliyuncs.com
      - name: build and push image
        run: |
          chmod +x ./build-be-department.sh
          ./build-be-department.sh  ${{ secrets.IMAGE_REPO }}
  build-be-elecprice:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # 设置 Docker Buildx（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        # 登录阿里云 Docker Registry
      - name: Log in to Aliyun Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          registry: crpi-vgud82zncz8nwfuc.cn-hangzhou.personal.cr.aliyuncs.com
      - name: build and push image
        run: |
          chmod +x ./build-be-elecprice.sh
          ./build-be-elecprice.sh  ${{ secrets.IMAGE_REPO }}
  build-be-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # 设置 Docker Buildx（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        # 登录阿里云 Docker Registry
      - name: Log in to Aliyun Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          registry: crpi-vgud82zncz8nwfuc.cn-hangzhou.personal.cr.aliyuncs.com
      - name: build and push image
        run: |
          chmod +x ./build-be-feed.sh
          ./build-be-feed.sh  ${{ secrets.IMAGE_REPO }}
  build-be-grade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # 设置 Docker Buildx（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        # 登录阿里云 Docker Registry
      - name: Log in to Aliyun Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          registry: crpi-vgud82zncz8nwfuc.cn-hangzhou.personal.cr.aliyuncs.com
      - name: build and push image
        run: |
          chmod +x ./build-be-grade.sh
          ./build-be-grade.sh  ${{ secrets.IMAGE_REPO }}
  build-be-infosum:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # 设置 Docker Buildx（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        # 登录阿里云 Docker Registry
      - name: Log in to Aliyun Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          registry: crpi-vgud82zncz8nwfuc.cn-hangzhou.personal.cr.aliyuncs.com
      - name: build and push image
        run: |
          chmod +x ./build-be-infosum.sh
          ./build-be-infosum.sh  ${{ secrets.IMAGE_REPO }}
  build-be-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # 设置 Docker Buildx（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        # 登录阿里云 Docker Registry
      - name: Log in to Aliyun Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          registry: crpi-vgud82zncz8nwfuc.cn-hangzhou.personal.cr.aliyuncs.com
      - name: build and push image
        run: |
          chmod +x ./build-be-website.sh
          ./build-be-website.sh  ${{ secrets.IMAGE_REPO }}
  build-bff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # 设置 Docker Buildx（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        # 登录阿里云 Docker Registry
      - name: Log in to Aliyun Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          registry: crpi-vgud82zncz8nwfuc.cn-hangzhou.personal.cr.aliyuncs.com
      - name: build and push image
        run: |
          chmod +x ./build-bff.sh
          ./build-bff.sh  ${{ secrets.IMAGE_REPO }}
  build-be-user:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # 设置 Docker Buildx（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        # 登录阿里云 Docker Registry
      - name: Log in to Aliyun Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          registry: crpi-vgud82zncz8nwfuc.cn-hangzhou.personal.cr.aliyuncs.com
      - name: build and push image
        run: |
          chmod +x ./build-be-user.sh
          ./build-be-user.sh  ${{ secrets.IMAGE_REPO }}  ${{ secrets.CRYPTO_KEY }}
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-be-banner
      - build-be-calendar
      - build-be-ccnu
      - build-be-class
      - build-be-classlist
      - build-be-counter
      - build-be-department
      - build-be-elecprice
      - build-be-feed
      - build-be-grade
      - build-be-infosum
      - build-be-website
      - build-bff
      - build-be-user
    steps:
      # 设置 SSH 密钥以便进行无密码登录
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: SSH into server and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_ADDR }} << 'EOF'
            cd ~/ccnubox
            kubectl apply -f namespace.yaml
            kubectl apply -f config-map.yaml
            kubectl apply -f mysql-svc.yaml
            kubectl apply -f redis-svc.yaml
            kubectl apply -f es-svc.yaml
            kubectl apply -f kafka-svc.yaml
            kubectl apply -f etcd-svc.yaml
            kubectl exec -it etcd-0 -n ccnube -- etcdctl user add root: || true
            kubectl exec -it etcd-0 -n ccnube -- etcdctl role add root || true
            kubectl exec -it etcd-0 -n ccnube -- etcdctl user grant-role root root || true
            kubectl exec -it etcd-0 -n ccnube -- etcdctl auth enable || true
            kubectl apply -f be-svc.yaml
          EOF
