name: 部署各个服务到集群


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-be-banner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          # 设置 Docker Buildx（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: build and push image
        run: |
          ./build-be-banner.sh  ${{ secrets.IMAGE_REPO }}
  build-be-calendar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # 设置 Docker Buildx（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: build and push image
        run: |
          ./build-be-calendar.sh  ${{ secrets.IMAGE_REPO }}
  build-be-ccnu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # 设置 Docker Buildx（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: build and push image
        run: |
          ./build-be-ccnu.sh  ${{ secrets.IMAGE_REPO }}
  build-be-class:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # 设置 Docker Buildx（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: build and push image
        run: |
          ./build-be-class.sh  ${{ secrets.IMAGE_REPO }}
  build-be-classlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # 设置 Docker Buildx（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: build and push image
        run: |
          ./build-be-classlist.sh  ${{ secrets.IMAGE_REPO }}
  build-be-counter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # 设置 Docker Buildx（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: build and push image
        run: |
          ./build-be-counter.sh  ${{ secrets.IMAGE_REPO }}
  build-be-department:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # 设置 Docker Buildx（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: build and push image
        run: |
          ./build-be-department.sh  ${{ secrets.IMAGE_REPO }}
  build-be-elecprice:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # 设置 Docker Buildx（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: build and push image
        run: |
          ./build-be-elecprice.sh  ${{ secrets.IMAGE_REPO }}
  build-be-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # 设置 Docker Buildx（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: build and push image
        run: |
          ./build-be-feed.sh  ${{ secrets.IMAGE_REPO }}
  build-be-grade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # 设置 Docker Buildx（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: build and push image
        run: |
          ./build-be-grade.sh  ${{ secrets.IMAGE_REPO }}
  build-be-infosum:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # 设置 Docker Buildx（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: build and push image
        run: |
          ./build-be-infosum.sh  ${{ secrets.IMAGE_REPO }}
  build-be-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # 设置 Docker Buildx（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: build and push image
        run: |
          ./build-be-website.sh  ${{ secrets.IMAGE_REPO }}
  build-bff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # 设置 Docker Buildx（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: build and push image
        run: |
          ./build-bff.sh  ${{ secrets.IMAGE_REPO }}
  build-be-user:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # 设置 Docker Buildx（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: build and push image
        run: |
          ./build-be-user.sh  ${{ secrets.IMAGE_REPO }}  ${{ secrets.CRYPTO_KEY }}
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-be-banner
      - build-be-calendar
      - build-be-ccnu
      - build-be-class
      - build-be-classlist
      - build-be-counter
      - build-be-department
      - build-be-elecprice
      - build-be-feed
      - build-be-grade
      - build-be-infosum
      - build-be-website
      - build-bff
      - build-be-user
    steps:
      # 设置 SSH 密钥以便进行无密码登录
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_ADDR }} >> ~/.ssh/known_hosts
      - name: SSH into server and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_ADDR }} << 'EOF'
            cd ~/ccnubox
            kubectl apply -f namespace.yaml
            kubectl apply -f config-map.yaml
            kubectl apply -f mysql-svc.yaml
            kubectl apply -f redis-svc.yaml
            kubectl apply -f es-svc.yaml
            kubectl apply -f kafka-svc.yaml
            kubectl apply -f etcd-svc.yaml
            kubectl exec -it etcd-0 -n ccnube -- etcdctl user add root:
            kubectl exec -it etcd-0 -n ccnube -- etcdctl role add root
            kubectl exec -it etcd-0 -n ccnube -- etcdctl user grant-role root root
            kubectl exec -it etcd-0 -n ccnube -- etcdctl auth enable
            kubectl apply -f be-svc.yaml
          EOF
